version: 2

models:
  - name: mass_decoded_dex_trades
    meta:
      blockchain: arbitrum, avalanche_c, base, bnb, celo, ethereum, fantom, gnosis, optimism, polygon, scroll, zksync, linea, blast, sei
      sector: dex
      contributors: 0xRob, hosuke, jeff-dude, tomfutago
    config:
      tags: [ 'dex', 'trades', 'beta' ]
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - blockchain
            - project
            - version
            - tx_hash
            - evt_index